[package]
name = "svc-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
# The web framework for handling HTTP requests (like /health) and upgrading to WebSockets
axum = "0.8.6"

# The asynchronous runtime
tokio = { version = "1", features = ["full"] }

# The WebSocket library
tokio-tungstenite = "0.28.0"

# For serializing and deserializing JSON messages (what you'll send over the WebSocket)
serde = { version = "1", features = ["derive"] }
serde_json = "1"
